survey_type = {
    1: "Human",
    2: "Animal"
}

# standard fields that are set based on sampling site
md_lookup = {
    'Hair':
        {'BODY_PRODUCT': 'UBERON:sebum',
         'COMMON_NAME': 'human skin metagenome',
         'SAMPLE_TYPE': 'Hair',
         'SCIENTIFIC_NAME': 'Homo sapiens sapiens',
         'TAXON_ID': '539655',
         'BODY_HABITAT': 'UBERON:hair',
         'ENV_MATTER': 'ENVO:sebum',
         'DESCRIPTION': 'American Gut Project Hair sample',
         'BODY_SITE': 'UBERON:hair'},
    'Nares': {
        'BODY_PRODUCT': 'UBERON:mucus',
        'COMMON_NAME': 'human nasal/pharyngeal metagenome',
        'SAMPLE_TYPE': 'Nares',
        'SCIENTIFIC_NAME': 'Homo sapiens sapiens',
        'TAXON_ID': '1131769',
        'BODY_HABITAT': 'UBERON:nose',
        'ENV_MATTER': 'ENVO:mucus',
        'DESCRIPTION': 'American Gut Project Nares sample',
        'BODY_SITE': 'UBERON:nostril'},
    'Vaginal mucus': {
        'BODY_PRODUCT': 'UBERON:mucus',
        'COMMON_NAME': 'vaginal metagenome',
        'SAMPLE_TYPE': 'Vaginal mucus',
        'SCIENTIFIC_NAME': 'Homo sapiens sapiens',
        'TAXON_ID': '1549736',
        'BODY_HABITAT': 'UBERON:vagina',
        'ENV_MATTER': 'ENVO:mucus',
        'DESCRIPTION': 'American Gut Project Vaginal mucus sample',
        'BODY_SITE': 'UBERON:vaginal introitus'},
    'Sole of foot': {
        'BODY_PRODUCT': 'UBERON:sebum',
        'COMMON_NAME': 'human skin metagenome',
        'SAMPLE_TYPE': 'Sole of foot',
        'SCIENTIFIC_NAME': 'Homo sapiens sapiens',
        'TAXON_ID': '539655',
        'BODY_HABITAT': 'UBERON:skin',
        'ENV_MATTER': 'ENVO:sebum',
        'DESCRIPTION': 'American Gut Project Sole of foot sample',
        'BODY_SITE': 'UBERON:skin of foot'},
    'Nasal mucus': {
        'BODY_PRODUCT': 'UBERON:mucus',
        'COMMON_NAME': 'human nasal/pharyngeal metagenome',
        'SAMPLE_TYPE': 'Nasal mucus',
        'SCIENTIFIC_NAME': 'Homo sapiens sapiens',
        'TAXON_ID': '1131769',
        'BODY_HABITAT': 'UBERON:nose',
        'ENV_MATTER': 'ENVO:mucus',
        'DESCRIPTION': 'American Gut Project Nasal mucus sample',
        'BODY_SITE': 'UBERON:nostril'},
    'Stool': {
        'BODY_PRODUCT': 'UBERON:feces',
        'COMMON_NAME': 'human gut metagenome',
        'SAMPLE_TYPE': 'Stool',
        'SCIENTIFIC_NAME': 'Homo sapiens sapiens',
        'TAXON_ID': '408170',
        'BODY_HABITAT': 'UBERON:feces',
        'ENV_MATTER': 'ENVO:feces',
        'DESCRIPTION': 'American Gut Project Stool sample',
        'BODY_SITE': 'UBERON:feces'},
    'Forehead': {
        'BODY_PRODUCT': 'UBERON:sebum',
        'COMMON_NAME': 'human skin metagenome',
        'SAMPLE_TYPE': 'Forehead',
        'SCIENTIFIC_NAME': 'Homo sapiens sapiens',
        'TAXON_ID': '539655',
        'BODY_HABITAT': 'UBERON:skin',
        'ENV_MATTER': 'ENVO:sebum',
        'DESCRIPTION': 'American Gut Project Forehead sample',
        'BODY_SITE': 'UBERON:skin of head'},
    'Tears': {
        'BODY_PRODUCT': 'UBERON:tears',
        'COMMON_NAME': 'human metagenome',
        'SAMPLE_TYPE': 'Tears',
        'SCIENTIFIC_NAME': 'Homo sapiens sapiens',
        'TAXON_ID': '646099',
        'BODY_HABITAT': 'UBERON:eye',
        'ENV_MATTER': 'ENVO:tears',
        'DESCRIPTION': 'American Gut Project Tears sample',
        'BODY_SITE': 'UBERON:eye'},
    'Right hand': {
        'BODY_PRODUCT': 'UBERON:sebum',
        'COMMON_NAME': 'human skin metagenome',
        'SAMPLE_TYPE': 'Right Hand',
        'SCIENTIFIC_NAME': 'Homo sapiens sapiens',
        'TAXON_ID': '539655',
        'BODY_HABITAT': 'UBERON:skin',
        'ENV_MATTER': 'ENVO:sebum',
        'DESCRIPTION': 'American Gut Project Right Hand sample',
        'BODY_SITE': 'UBERON:skin of hand'},
    'Mouth': {
        'BODY_PRODUCT': 'UBERON:saliva',
        'COMMON_NAME': 'human oral metagenome',
        'SAMPLE_TYPE': 'Mouth',
        'SCIENTIFIC_NAME': 'Homo sapiens sapiens',
        'TAXON_ID': '447426',
        'BODY_HABITAT': 'UBERON:oral cavity',
        'ENV_MATTER': 'ENVO:saliva',
        'DESCRIPTION': 'American Gut Project Mouth sample',
        'BODY_SITE': 'UBERON:tongue'},
    'Left hand': {
        'BODY_PRODUCT': 'UBERON:sebum',
        'COMMON_NAME': 'human skin metagenome',
        'SAMPLE_TYPE': 'Left Hand',
        'SCIENTIFIC_NAME': 'Homo sapiens sapiens',
        'TAXON_ID': '539655',
        'BODY_HABITAT': 'UBERON:skin',
        'ENV_MATTER': 'ENVO:sebum',
        'DESCRIPTION': 'American Gut Project Left Hand sample',
        'BODY_SITE': 'UBERON:skin of hand'},
    'Ear wax': {
        'BODY_PRODUCT': 'UBERON:ear wax',
        'COMMON_NAME': 'human metagenome',
        'SAMPLE_TYPE': 'Ear wax',
        'SCIENTIFIC_NAME': 'Homo sapiens sapiens',
        'TAXON_ID': '646099',
        'BODY_HABITAT': 'UBERON:ear',
        'ENV_MATTER': 'ENVO:ear wax',
        'DESCRIPTION': 'American Gut Project Ear wax sample',
        'BODY_SITE': 'UBERON:external auditory meatus'}
}

month_lookup = {'January': 1, 'February': 2, 'March': 3,
                'April': 4, 'May': 5, 'June': 6,
                'July': 7, 'August': 8, 'September': 9,
                'October': 10, 'November': 11, 'December': 12}
