#!/usr/bin/env python

from __future__ import division

from os import makedirs
from os.path import join

import click

from knimin.lib.util import combine_barcodes
from knimin import db

__author__ = "Adam Robbins-Pianka"
__copyright__ = "Copyright 2009-2015, QIIME Web Analysis"
__credits__ = ["Adam Robbins-Pianka"]
__license__ = "GPL"
__version__ = "1.0.0"
__maintainer__ = ["Adam Robbins-Pianka"]
__email__ = "adam.robbinspianka@colorado.edu"
__status__ = "Development"


@click.group()
def cli():
    """All commands in this click group will be available at the top level
    """
    pass


@cli.command()
@click.option('-i', '--input-file', required=False,
              type=click.File('U'),
              help="Path to file containing barcodes, one per line")
@click.option('-o', '--output-dir', required=True,
              type=click.Path(exists=False, readable=True, writable=True))
@click.argument('barcodes', nargs=-1)
def pulldown(input_file, output_dir, barcodes):
    if not barcodes and input_file is None:
        click.echo("You must specify either an input file (-i) or at least "
                   "one barcode")

    all_barcodes = combine_barcodes(barcodes, input_file)
    metadata, failures = db.pulldown(all_barcodes)
    makedirs(output_dir)

    for survey, barcodes_responses in metadata.items():
        with open(join(output_dir,
                       'survey_%d_md.txt' % survey), 'w') as outfile:
            outfile.write(barcodes_responses)

    if failures:
        click.echo("The following barcodes were not retrieved for any survey:"
                   "\n%s\n" % '\n'.join(sorted(failures)))


if __name__ == '__main__':
    cli()
